# LOGISTIC REGRESSION

# LOAD THE DATASET

In [1]:
import numpy as np

In [2]:
x=np.arange(11).reshape(-1,1)

In [4]:

x.shape

(11, 1)

In [51]:
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [52]:
y=np.array([0,0,0,0,1,1,1,1,1,1,0])

In [53]:
y.shape

(11,)

# IMPORT LOGESTIC REGRESSION ALGORITHM

In [10]:
from sklearn.linear_model import LogisticRegression

# create amodel

In [11]:
model=LogisticRegression()

# fit the model

In [54]:
model.fit(x,y)

LogisticRegression()

In [55]:
model.coef_

array([[0.37841917]])

In [56]:
model.intercept_

array([-1.64875086])

# PREDICT THE PROBABILITES

In [57]:
model.predict_proba(x)

array([[0.83872215, 0.16127785],
       [0.78079952, 0.21920048],
       [0.70928469, 0.29071531],
       [0.62562504, 0.37437496],
       [0.5337173 , 0.4662827 ],
       [0.4394622 , 0.5605378 ],
       [0.34938033, 0.65061967],
       [0.26890538, 0.73109462],
       [0.20123354, 0.79876646],
       [0.14716375, 0.85283625],
       [0.10569958, 0.89430042]])

In [58]:
model.score(x,y)

0.8181818181818182

In [59]:
y_pred=model.predict(x)

In [63]:
y_pred

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [60]:
from sklearn.metrics import classification_report,confusion_matrix

In [61]:
model.score(x,y)

0.8181818181818182

In [72]:
confusion_matrix(y,y_pred)

array([[4, 1],
       [1, 5]])

In [35]:
pip install collections-extended

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [67]:
from collections import Counter

In [68]:
Counter(y)

Counter({0: 5, 1: 6})

In [69]:
y

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0])

In [70]:
y_pred

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [71]:
Counter(y_pred)

Counter({0: 5, 1: 6})

In [74]:
from sklearn.metrics import classification_report,confusion_matrix

In [76]:
print(classification_report(y,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.80      0.80         5
           1       0.83      0.83      0.83         6

    accuracy                           0.82        11
   macro avg       0.82      0.82      0.82        11
weighted avg       0.82      0.82      0.82        11

