In [3]:
import pandas as pd
import numpy as np

In [15]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from collections import Counter


In [4]:
x=np.arange(5).reshape(-1,1)

In [5]:
y=np.array([1,0,1,1,0])

In [6]:
x

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [7]:
y

array([1, 0, 1, 1, 0])

In [8]:
lrm1=LogisticRegression()

In [9]:
lrm1.fit(x,y)

LogisticRegression()

In [10]:
lrm1.predict_proba(x)

array([[0.26461804, 0.73538196],
       [0.32680134, 0.67319866],
       [0.39573372, 0.60426628],
       [0.46907483, 0.53092517],
       [0.54377659, 0.45622341]])

In [11]:
y_pred=lrm1.predict(x)

In [12]:
y_pred

array([1, 1, 1, 1, 0])

In [13]:
y

array([1, 0, 1, 1, 0])

In [14]:
y_pred

array([1, 1, 1, 1, 0])

In [17]:
Counter(y)

Counter({1: 3, 0: 2})

In [18]:
Counter(y_pred)

Counter({1: 4, 0: 1})

In [19]:
confusion_matrix(y,y_pred)

array([[1, 1],
       [0, 3]])

In [21]:
print(classification_report(y,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.75      1.00      0.86         3

    accuracy                           0.80         5
   macro avg       0.88      0.75      0.76         5
weighted avg       0.85      0.80      0.78         5

